#!/bin/sh

# Copyright 2020 BlackYau <blackyau426@gmail.com>
# GNU General Public License v3.0

# Place in /etc/hotplug.d/iface

enable=$(uci get suselogin.@login[0].enable)
[ $enable -eq 0 ] && exit 0

dir="/tmp/log/suselogin/" && mkdir -p ${dir}
logfile="${dir}suselogin.log"
ua="User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36"

function isonline(){
	local captiveReturnCode=`curl -s -I -m 10 -o /dev/null -s -w %{http_code} http://www.google.cn/generate_204`
	if [ "$captiveReturnCode" = "204" ]; then
		return
	fi
	false
}

function up(){
	if isonline; then
		echo "$(date "+%Y-%m-%d %H:%M:%S"): 您已连接到网络(hotplug)" >> ${logfile}
		sleep 1 && return
	fi

	# Get referer page
	local refererPage=`curl -s "http://www.google.cn/generate_204" | awk -F \' '{print $2}'`

	# Structure loginURL
	local loginURL=`echo $refererPage | awk -F \? '{print $1}'`
	local loginURL="${loginURL/index.jsp/InterFace.do?method=login}"

	# Structure queryString
	local queryString=`echo $refererPage | awk -F \? '{print $2}'`
	local queryString="${queryString//&/%2526}"
	local queryString="${queryString//=/%253D}"

	# Login
	if [ -n "$loginURL" ]; then
		ip=$(ifconfig eth0 | grep 'inet addr:' | grep -oE '([0-9]{1,3}.){3}.[0-9]{1,3}' | head -n 1)
		curl "http://111.17.200.130:801/eportal/portal/login?callback=dr1003&login_method=1&user_account=${username}&user_password=${password}&wlan_user_ip=${ip}&wlan_user_ipv6=&wlan_user_mac=000000000000&wlan_ac_ip=&wlan_ac_name=&jsVersion=4.2.1&terminal_type=1&lang=zh-cn&v=6915&lang=zh" \
			"$loginURL" > ${dir}login.log
		wait
	else
		echo "$(date "+%Y-%m-%d %H:%M:%S"): 获取登录地址失败(hotplug)" >> ${logfile} && return
	fi

	if isonline; then
		ntpd -n -q -p ntp1.aliyun.com  # 登录成功后校准时间
		wait # 等待校准时间完毕
		echo "$(date "+%Y-%m-%d %H:%M:%S"): 登录成功(hotplug)" >> ${logfile} && sleep 2 && return
	else
		echo -n "$(date "+%Y-%m-%d %H:%M:%S"): 登录失败,错误信息(hotplug): " >> ${logfile}
		echo "$(cat /tmp/log/suselogin/login.log)" >> ${logfile}
	fi
}

if [ "$INTERFACE" = wan ]; then  # Place in /etc/hotplug.d/iface
	if [ "$ACTION" = ifup ]; then
		echo "$(date "+%Y-%m-%d %H:%M:%S"): 检测到 WAN 口状态变化,准备尝试拨号" >> ${logfile}
		username=$(uci get suselogin.@login[0].username)
		password=$(uci get suselogin.@login[0].password)
		isp=$(uci get suselogin.@login[0].isp)
		up
	fi
fi
exit 0
